"""Turn functions/api/_kb_riskguard.txt into lib/kb_riskguard.js (a JS module exporting
the text). Run after editing the knowledge base:  python lib/build_kb.py

Why a generated module: Pages Functions bundle JavaScript reliably; importing raw .txt
depends on bundler rules. The text is escaped so backticks and ${ cannot break out of the
template literal."""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "functions" / "api" / "_kb_riskguard.txt"
dst = root / "lib" / "kb_riskguard.js"
text = src.read_text(encoding="utf-8") if src.exists() else "(RiskGuard knowledge base not written yet.)"
esc = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
dst.write_text("// GENERATED by lib/build_kb.py from functions/api/_kb_riskguard.txt — edit the .txt, not this.\n"
               f"export default `{esc}`;\n", encoding="utf-8")
print(f"{dst} written, {len(text)} characters")
